### ISSUE TITLE
/getOrgID base64 Decoder

### ISSUE THREAD

**Issue by phoebeww** [Alex-XJK/100-of-100-service-team#34]
Currently, the backend accepts any base64-decoded ID and returns a status 200 even if the ID doesn’t exist in the database. Validation for the decoded ID to ensure it matches a real organization before responding is needed; we also need to handle registration as to encode the input strings to a valid id.

**Comment by Alex-XJK** [comment]
Hi Phoebe,

Thank you so much for your comment and suggestion, and we have now addressed your issues in our project.

As of 17628ef, we enabled the organization existence check.
As of a4afbb8, we provided a brand new `/login` endpoint with enhanced security check.
Both of the commits had already been merged in PR #35.
As of ed2a4fc, we also implemented a `/register` endpoint that you suggested, and it should be reviewed soon.

Best,
Alex
